apiVersion: v1
kind: Service
metadata:
  name: my-node-app-service
  namespace: my-node-app
spec:
  type: NodePort
  selector:
    app: my-node-app
    version: {{ .Values.activeVersion }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP