name: Deploy with Blue-Green

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'helm/**'

jobs:
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}

  deploy:
    name: Deploy with Helm and Blue-Green Switch
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Helm values with new image
        run: |
          cd helm/my-node-app-chart
          current_version=$(yq eval '.activeVersion' values.yaml)
          if [ "$current_version" = "blue" ]; then
            # Update green with new version
            yq eval '.green.image.tag = "${{ github.sha }}"' -i values.yaml
          else
            # Update blue with new version
            yq eval '.blue.image.tag = "${{ github.sha }}"' -i values.yaml
          fi

      - name: Commit and push updated values
        run: |
          git config --global user.name 'IfeOlaitan'
          git config --global user.email 'ifeoluwa1201@gmail.com'
          git add helm/my-node-app-chart/values.yaml
          git commit -m "Update image tag for ${{ github.sha }}"
          git push