name: Deploy with Blue-Green

on:
  push:
    branches:
      - main
      - 'feat/**'  # Add feature branches
    paths-ignore:
      - '**.md'
      - 'helm/**'
  pull_request:
    branches: [ main ]

jobs:
  push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/my-node-app:${{ github.sha }}

  deploy:
    name: Deploy with Helm and Blue-Green Switch
    needs: push
    runs-on: ubuntu-latest
    # Only run deployment steps on main branch
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}

      - name: Update Helm values with new image
        run: |
          cd helm/my-node-app-chart
          yq eval '.image.repository = "${{ secrets.DOCKERHUB_USERNAME }}/my-node-app"' -i values.yaml
          yq eval '.image.tag = "${{ github.sha }}"' -i values.yaml

      # Script switches the activeVersion between blue and green deployments.
      - name: Switch active version (Blue-Green)
        run: |
          cd helm/my-node-app-chart
          if yq eval '.activeVersion' values.yaml | grep -q 'blue'; then
            yq eval '.activeVersion = "green"' -i values.yaml
          else
            yq eval '.activeVersion = "blue"' -i values.yaml
          fi

      - name: Commit and push updated values
        run: |
          git config --global user.name 'IfeOlaitan'
          git config --global user.email 'ifeoluwa1201@gmail.com'
          git add helm/my-node-app-chart/values.yaml
          git commit -m "Update image tag and switch active version to ${{ github.sha }}"
          git push